title: rabbithole
description: Alice, one synonym at a time
url: "https://shouldfeelright.github.io"
baseurl: "/rabbithole"

exclude:
  - baseline.md
  - update-readme.py
  - build_timeline.py
  - .history.json
  - Gemfile
  - Gemfile.lock
  - README.md
