name: Update README

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
             pip install nltk
             pip install spacy
             pip install pyinflect
             python -m spacy download en_core_web_sm

      - name: Run update script multiple times
        run: |
          RUNS=$((RANDOM % 5 + 1))
          echo "Will run script $RUNS times"
          for i in $(seq 1 $RUNS); do
            echo "Running iteration $i of $RUNS"
            python update-readme.py
            git config user.name "shouldfeelright"
            git config user.email "shouldfeelright@proton.me"
            git add README.md .history.json
            git commit -m "Update README.md (run $i of $RUNS)" || echo "No changes to commit"
            git push
          done
